from domain.tax.tax_band import TaxBand

PERSONAL_ALLOWANCE: float = 12570
HIGHER_THRESHOLD: float = 50270
ADDITIONAL_THRESHOLD: float = 125140

INCOME_TAX_BANDS = [
    TaxBand(0, PERSONAL_ALLOWANCE, 0.0),
    TaxBand(PERSONAL_ALLOWANCE + 1, HIGHER_THRESHOLD, 0.20),
    TaxBand(HIGHER_THRESHOLD + 1, ADDITIONAL_THRESHOLD, 0.40),
    TaxBand(ADDITIONAL_THRESHOLD, float("inf"), 0.45)
]
